# IMPORTANT: use "ifc" allways as a prefix name for all of IFC instances and do not add any prefix URI for them.
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX simcore: <http://www.opteemal.eu/schema/2017/01/SimModelCore#>
PREFIX simres: <http://www.opteemal.eu/schema/2017/01/ResourcesGeneral#>
PREFIX simgeom: <http://www.opteemal.eu/schema/2017/01/ResourcesGeometry#>
PREFIX simbldg: <http://www.opteemal.eu/schema/2017/01/BuildingModel#>
PREFIX simmep: <http://www.opteemal.eu/schema/2017/01/MepModel#>
PREFIX simmodel: <http://www.opteemal.eu/schema/2017/01/Model#>


# last motifcation 2018.07.03

CONSTRUCT
{
	# PART 1 SimModel instance --------------------------------------------
	?SimModel_ID1 
		rdf:type 									simmodel:SimModel ;
		simmodel:simVirtualElement_Default_Default 	?IfcVirtualElement;
		.		
		
	# PART 2 SimWall ExteriorAboveGrade Instance ----------------------	
	?IfcVirtualElement 
		rdf:type 							simbldg:SimVirtualElement_Default_Default ;
		simcore:ifcGlobalID 				?IfcGloballyUniqueIdValue ;
		simcore:isTemplateObject 			"false"^^xsd:boolean ;
		simcore:name 						?name_IfcRootValue ; 			
		simcore:objectType 					"VirtualElement"^^xsd:string ;  
		simcore:refId 						?simVirtualElementRefId ;
		simcore:simModelSubtype 			"Default"^^xsd:string ;		
		simcore:simModelType 				"VirtualElement"^^xsd:string ;
		simcore:simUniqueID 				"not defined" ;
		simcore:sourceModelObjectType 		"IfcVirtualElement"^^xsd:string ;
		simcore:sourceModelSchema 			"IFC4" ;
		simcore:tag 						"not defined" ;
		.		
	
}
WHERE 
{
	# PART 1 General information --------------------------------------------
	?IfcVirtualElement rdf:type ifc:IfcVirtualElement ;
		ifc:globalId_IfcRoot [express:hasString ?IfcGloballyUniqueIdValue ] ;
		ifc:name_IfcRoot [express:hasString ?name_IfcRootValue ] ;
		.
		
	#bind( strafter( xsd:string(?IfcWall), "IfcWall_" ) as ?simWallRefId ).
	bind( (xsd:ID(CONCAT("ID", strafter( xsd:string(?IfcVirtualElement), "IfcVirtualElement_" )))) as ?simVirtualElementRefId ) .
	
	# ID of SimModel_ID1 (get the instance base URI + SimModel_ID1)
	bind( URI(CONCAT(STRBEFORE( xsd:string(?IfcVirtualElement), "IfcVirtualElement_" ), "SimModel_ID1")) as ?SimModel_ID1 ) .
}




